config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # all tasks
  get "tasks", to: "tasks#index", as: :tasks

  # create a task
  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'

  # one task
  get 'tasks/:id', to: 'tasks#show', as: :task

  # update a task
  get 'tasks/:id/edit', to: 'tasks#edit', as: :task_edit
  patch 'tasks/:id', to: 'tasks#update'

  # # delete
  delete 'tasks/:id', to: 'tasks#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    Task.create(task_params)
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    task = Task.find(params[:id])
    task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/6ee6083bbd.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
 <%= f.label :title %>
 <%= f.text_field :title %>
 <%= f.label :details %>
 <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>List of tasks</h1>

<ul style="list-style-type:none;">
  <% @tasks.each do |task| %>
    <% if task.completed %>
      <li class ="list-item">
        <%= link_to task_path(task.id) do  %>
          <i class="far fa-check-circle"></i> <%= task.title %>
        <% end %>
      </li>
      <% else %>
        <li class = "list-item">
          <%= link_to task_path(task.id) do  %>
            <i class="far fa-circle"></i> <%= task.title %>
          <% end %>
        </li>
    <% end %>

  <% end %>
</ul>

<%= link_to tasks_new_path do %>
  <p><i class="fas fa-plus"></i> Add a task</p>
<% end %>

app/views/tasks/new.html.erb
<%= render 'form', task: @task, completed: false %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>

<h3><%= @task.details %></h3>


<% if @task.completed %>
  <li>
    <p><i class="far fa-check-circle"></i> This task is completed</p>
  </li>
  <% else %>
    <li>
      <p><i class="far fa-circle"></i> This task is not completed yet</p>
    </li>
<% end %>

<%= link_to tasks_path do %>
  <p><i class="fas fa-undo-alt"></i> Back to list</p>
<% end %>

<%= link_to task_edit_path(params[:id]) do %>
<p><i class="fas fa-edit"></i> Edit post</p>
<% end %>

<%= link_to task_path(params[:id]), method: :delete do  %>
<p><i class="fas fa-trash-alt"></i> Delete task</p>
<% end %>